- frontend/src/app/oe/components/blockspan-navigator/blockspan-navigator.component.html
- frontend/src/app/oe/components/blockspan-navigator/blockspan-navigator.component.ts
- frontend/src/app/oe/components/blockspans-home/blockspans-home.component.html
- frontend/src/app/oe/components/blockspans-home/blockspans-home.component.ts
- frontend/src/app/oe/components/preview/preview.component.ts
- frontend/src/app/oe/oe.routing.modules.ts
- frontend/src/app/oe/utils/helper.ts
- frontend/src/environments/environment.prod.ts
- frontend/src/environments/environment.ts
- Added support for multiple editable text boxs 
- Added support for change blockspan numbers using URL
- Refactored somecode and added proper error messages in UI
> Updated Blockspan screen 

- .github/workflows/op-energy.yml
- ci-tests.nix
this PR is for refreshed github actions
> fix: fix github actions

- .github/workflows/dev-deploy.yml
> Gh actions refresh

- frontend/src/app/oe/components/about/about.component.html
Added about us page with whitepaper link and announcement link
> Added about us page with whitepaper link and announcement link

- frontend/src/app/oe/components/strike-detail/strike-detail.component.html
- frontend/src/app/oe/components/strike-detail/strike-detail.component.ts
Fixed Strike detail Link issue
> Fixed Strike detail Link issue

- frontend/src/app/oe/components/about/about.component.html
> Issue-10 Added FAQ doc link

- frontend/src/app/oe/components/about/about.component.html
this PR fixes git commit url in the about page to a proper repo
> fix: commit url

- frontend/src/app/oe/components/blockspans-home/blockspans-home.component.ts
- frontend/src/app/oe/components/energy-detail/energy-detail.component.ts
- frontend/src/app/oe/components/strike-detail/strike-detail.component.html
- frontend/src/app/oe/components/strike-detail/strike-detail.component.ts
- frontend/src/app/oe/components/strike-summary/strike-summary.component.ts
- frontend/src/app/oe/components/strike/strike.component.html
- frontend/src/app/oe/components/strike/strike.component.ts
- frontend/src/app/oe/interfaces/oe-energy.interface.ts
- frontend/src/app/oe/services/oe-energy.service.ts
this PR replaces nlocktime with strikeMediantime and cleanup some deprecated api calls
> replace nlocktime with strikeMediantime + cleanup deprecated api calls

- frontend/src/app/oe/components/base-box/base-box.component.html
- frontend/src/app/oe/components/base-box/base-box.component.ts
- frontend/src/app/oe/components/energy-detail/energy-detail.component.html
- frontend/src/app/oe/components/energy-detail/energy-detail.component.ts
- frontend/src/app/oe/components/energy-summary/energy-summary.component.html
- frontend/src/app/oe/components/energy/energy.component.html
- frontend/src/app/oe/components/energy/energy.component.ts
Comparing main...25-one-unified-energy-detail-view · op-energy-foundation/op-energy-blockspan-servic
> 25 Added one unified energy view

- frontend/derivation.nix
- frontend/frontend-node-env.nix
- frontend/frontend-node-packages.nix
- frontend/package-lock.json
- frontend/package.json
Had to modify swagger-ui.css in order to satisfy postcss loader
> update swagger-ui-dist to 5.6.2

- frontend/src/app/oe/components/base-box-hor/base-box-hor.component.scss
- frontend/src/app/oe/components/blockspans-home/blockspans-home.component.ts
- frontend/src/app/oe/components/energy-detail/energy-detail.component.ts
- frontend/src/app/oe/components/strike-detail/strike-detail.component.html
- frontend/src/app/oe/components/strike-detail/strike-detail.component.scss
- frontend/src/app/oe/components/strike-detail/strike-detail.component.ts
- frontend/src/app/oe/components/strike-summary/strike-summary.component.ts
- frontend/src/app/oe/components/strike/strike.component.html
- frontend/src/app/oe/components/strike/strike.component.ts
- frontend/src/app/oe/interfaces/oe-energy.interface.ts
- frontend/src/app/oe/services/oe-energy.service.ts
- Added code changes to display strike with guess details
> Added code changes to display strike with guess details

- README.md
This PR introduces README.md with basic info for now.
best viewed in a rendered mode by accessing https://github.com/op-energy-foundation/op-energy-blockspan-service/blob/documentation/README.md
> documentation: README.md

- frontend/src/app/oe/components/blockspans-home/blockspans-home.component.scss
- frontend/src/app/oe/components/preview/preview.component.html
- frontend/src/app/oe/components/preview/preview.component.ts
- frontend/src/app/oe/components/strikes-range/strikes-range.component.ts
- frontend/src/app/oe/interfaces/oe-energy.interface.ts
- Added lastStrikes and NextStrikes support for strikes
- fixed left margin issue for blockspans screen
> 15 Added lastStrikes and NextStrikes support for filtering strikes

- frontend/src/app/oe/components/preview/preview.component.html
- frontend/src/app/oe/components/preview/preview.component.ts
- frontend/src/app/oe/components/strikes-range/strikes-range.component.ts
- frontend/src/app/oe/components/strikes-range/strikes-range.interface.ts
issue-55: Added strike range screen based on guess
> issue-55: Added strike range screen based on guess

- frontend/src/app/oe/components/preview/preview.component.html
- frontend/src/app/oe/components/preview/preview.component.ts
issue-58 updated preview page to have link to nearest future block
> issue-58 updated preview page to have link to nearest future block

- frontend/src/app/oe/components/guessing-game/guessing-game.component.html
- frontend/src/app/oe/components/guessing-game/guessing-game.component.ts
- frontend/src/app/oe/components/login/login.component.ts
- frontend/src/app/oe/components/my-guesses/my-guesses.component.html
- frontend/src/app/oe/components/my-guesses/my-guesses.component.spec.ts
- frontend/src/app/oe/components/my-guesses/my-guesses.component.ts
- frontend/src/app/oe/components/preview/preview.component.html
- frontend/src/app/oe/components/preview/preview.component.ts
- frontend/src/app/oe/components/strikes-range/strikes-range.component.html
- frontend/src/app/oe/interceptors/auth.interceptor.ts
- frontend/src/app/oe/interfaces/oe-energy.interface.ts
- frontend/src/app/oe/oe.module.ts
- frontend/src/app/oe/oe.routing.modules.ts
- frontend/src/app/oe/services/oe-energy.service.ts
Added my guess screen and bug fixes
> Added my guess screen and bug fixes

- frontend/src/app/oe/components/blockspan-bhs/blockspan-bhs.component.html
- frontend/src/app/oe/components/blockspan-bhs/blockspan-bhs.component.scss
- frontend/src/app/oe/components/blockspan-bhs/blockspan-bhs.component.spec.ts
- frontend/src/app/oe/components/blockspan-bhs/blockspan-bhs.component.ts
- frontend/src/app/oe/components/box/box.component.html
- frontend/src/app/oe/components/box/box.component.scss
- frontend/src/app/oe/components/box/box.component.spec.ts
- frontend/src/app/oe/components/box/box.component.ts
- frontend/src/app/oe/components/preview/preview.component.html
- frontend/src/app/oe/components/preview/preview.component.ts
- frontend/src/app/oe/interfaces/oe-energy.interface.ts
- frontend/src/app/oe/oe.module.ts
- frontend/src/app/oe/oe.routing.modules.ts
- frontend/src/app/oe/types/constant.ts
- frontend/src/app/oe/utils/helper.ts
60 Added blockspan details view
> 60 Added blockspan details view

- frontend/src/app/oe/components/block-rate-strike-details-v2/block-rate-strike-details-v2.component.html
- frontend/src/app/oe/components/blockrate-strike-summary-v2/blockrate-strike-summary-v2.component.html
- frontend/src/app/oe/components/blockrate-strike-summary-v2/blockrate-strike-summary-v2.component.scss
- frontend/src/app/oe/components/blockrate-strike-summary-v2/blockrate-strike-summary-v2.component.spec.ts
- frontend/src/app/oe/components/blockrate-strike-summary-v2/blockrate-strike-summary-v2.component.ts
- frontend/src/app/oe/components/my-guesses/my-guesses.component.ts
- frontend/src/app/oe/components/preview/preview.component.html
- frontend/src/app/oe/components/preview/preview.component.ts
- frontend/src/app/oe/oe.module.ts
- frontend/src/app/oe/oe.routing.modules.ts
69 create new screen for block rate strike summary v2
> 69 create new screen for block rate strike summary v2

- frontend/frontend-node-packages.nix
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/app.module.ts
- frontend/src/app/oe/components/block-rate-strike-details-v2/block-rate-strike-details-v2.component.scss
- frontend/src/app/oe/components/block-rate-strike-details-v2/block-rate-strike-details-v2.component.ts
- frontend/src/app/oe/components/blockrate-strike-summary-v2/blockrate-strike-summary-v2.component.ts
- frontend/src/app/oe/components/blockrate-summary-v2/blockrate-summary-v2.component.ts
- frontend/src/app/oe/components/blockspan-bhs/blockspan-bhs.component.html
- frontend/src/app/oe/components/blockspan-bhs/blockspan-bhs.component.scss
- frontend/src/app/oe/components/blockspan-bhs/blockspan-bhs.component.ts
- frontend/src/app/oe/components/box/box.component.html
- frontend/src/app/oe/components/box/box.component.scss
- frontend/src/app/oe/components/box/box.component.ts
- frontend/src/app/oe/components/preview/preview.component.html
- frontend/src/app/oe/components/preview/preview.component.ts
- frontend/src/app/oe/components/strikes-range/strikes-range.component.ts
- frontend/src/app/oe/utils/helper.ts
Added suggested changes for blockspan details screen
> Added suggested changes for blockspan details screen

- op-energy-api/src/Data/OpEnergy/Client.hs
This PR introduces function withClientEither in order to be able to handle client error explicitly instead of throwing exception
> feat: introduce function withClientEither

- frontend/src/app/oe/components/block-rate-strike-details-v2/block-rate-strike-details-v2.component.ts
- frontend/src/app/oe/components/common/base-block/BaseBlockComponent.ts
This PR refactors the `BlockRateStrikeDetailsV2Component` to extend `BaseBlockComponent`, improving code reusability, maintainability, and reducing redundancy.
---
✅ **Extended `BaseBlockComponent`** instead of manually implementing shared logic.  
✅ **Removed redundant methods** that already exist in `BaseBlockComponent`, such as:  
- `initializeBlocks`  
- `initializeLatestBlock`  
- `processQueryParams`  
- `calculateBlockRange`  
- `handleError`  
✅ **Updated the constructor** to use `super()` for dependency injection.  
✅ **Refactored `ngOnInit()`** to utilize base class methods for block initialization and query param handling.  
✅ **Preserved unique methods** like `checkExistingGuess()`, which are specific to this component.
> Refactor BlockRateStrikeDetailsV2Component to Use BaseBlockComponent

- frontend/src/app/oe/components/blockrates-graph/block-rates-graph.component.ts
- frontend/src/app/oe/components/blockspan-bhs/blockspan-bhs.component.html
✅ **Removed Unused Fields from JSON and CSV charts data download**  
- Cleaned up exported data by eliminating extra/unnecessary fields.  
- Ensures lighter payloads and better data clarity for consumers.
✅ **Added `startTimestamp` and `endTimestamp` Fields**  
- Included both timestamps in the data output to improve context and filtering.  
- Available in both JSON and CSV exports.
✅ **Fixed Tooltip Bug on Blockspan Screen**  
- Resolved issue where tooltips were not appearing or updating as expected.  
- Tooltip behavior is now consistent with hover and value changes.
> This PR improves the data for charts by removing redundant fields, adding useful timestamp information, and resolving a UI bug related to tooltips.
